import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
pip install SpeechRecognition moviepy pydub flask
import speech_recognition as sr
from moviepy.editor import VideoFileClip
from pydub import AudioSegment
import os

# Set up a recognizer instance
recognizer = sr.Recognizer()

def convert_video_to_audio(video_path, audio_path):
    # Convert video to audio
        clip = VideoFileClip(video_path)
            clip.audio.write_audiofile(audio_path)

            def transcribe_audio(audio_path):
                # Load audio file
                    with sr.AudioFile(audio_path) as source:
                            audio_data = recognizer.record(source)
                                    # Perform speech-to-text
                                            try:
                                                        text = recognizer.recognize_google(audio_data)
                                                                    print("Transcription:", text)
                                                                                return text
                                                                                        except sr.UnknownValueError:
                                                                                                    print("Could not understand audio")
                                                                                                                return None
                                                                                                                        except sr.RequestError as e:
                                                                                                                                    print("Error with the Google Speech API:", e)
                                                                                                                                                return None

                                                                                                                                                # Example Usage
                                                                                                                                                video_path = "input_video.mp4"
                                                                                                                                                audio_path = "extracted_audio.wav"

                                                                                                                                                # Step 1: Convert Video to Audio
                                                                                                                                                convert_video_to_audio(video_path, audio_path)

                                                                                                                                                # Step 2: Transcribe Audio
                                                                                                                                                transcription = transcribe_audio(audio_path)
                                                                                                                                                import speech_recognition as sr
                                                                                                                                                from moviepy.editor import VideoFileClip
                                                                                                                                                from pydub import AudioSegment
                                                                                                                                                import os

                                                                                                                                                # Set up a recognizer instance
                                                                                                                                                recognizer = sr.Recognizer()

                                                                                                                                                def convert_video_to_audio(video_path, audio_path):
                                                                                                                                                    # Convert video to audio
                                                                                                                                                        clip = VideoFileClip(video_path)
                                                                                                                                                            clip.audio.write_audiofile(audio_path)

                                                                                                                                                            def transcribe_audio(audio_path):
                                                                                                                                                                # Load audio file
                                                                                                                                                                    with sr.AudioFile(audio_path) as source:
                                                                                                                                                                            audio_data = recognizer.record(source)
                                                                                                                                                                                    # Perform speech-to-text
                                                                                                                                                                                            try:
                                                                                                                                                                                                        text = recognizer.recognize_google(audio_data)
                                                                                                                                                                                                                    print("Transcription:", text)
                                                                                                                                                                                                                                return text
                                                                                                                                                                                                                                        except sr.UnknownValueError:
                                                                                                                                                                                                                                                    print("Could not understand audio")
                                                                                                                                                                                                                                                                return None
                                                                                                                                                                                                                                                                        except sr.RequestError as e:
                                                                                                                                                                                                                                                                                    print("Error with the Google Speech API:", e)
                                                                                                                                                                                                                                                                                                return None

                                                                                                                                                                                                                                                                                                # Example Usage
                                                                                                                                                                                                                                                                                                video_path = "input_video.mp4"
                                                                                                                                                                                                                                                                                                audio_path = "extracted_audio.wav"

                                                                                                                                                                                                                                                                                                # Step 1: Convert Video to Audio
                                                                                                                                                                                                                                                                                                convert_video_to_audio(video_path, audio_path)

                                                                                                                                                                                                                                                                                                # Step 2: Transcribe Audio
                                                                                                                                                                                                                                                                                                transcription = transcribe_audio(audio_path)
                                                                                                                                                                                                                                                                                                